name: build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "20.2.0"
          java-version: "java11"
          native-image: "true"
      - name: Build & Unit tests
        run: mvn --batch-mode clean install
      - name: Integration tests
        run: |
          mvn --batch-mode clean package -DskipTests -Dnative -pl tests -amd
          cd tests/pg-test
          docker build -t $(echo "$PWD" | sed 's!.*/!!') -f src/main/docker/Dockerfile .
          cd ../mysql-test
          docker build -t $(echo "$PWD" | sed 's!.*/!!') -f src/main/docker/Dockerfile .
          cd ../..
          mvn --batch-mode failsafe:integration-test failsafe:verify -pl tests -amd
